on:
  push

name: Test Find and Transition Issue Keys

jobs:
  test-find-and-transition-issue-keys:
    name: Find and Transition Issue Keys
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Find and Transition Issue Key
      uses: ./
      with:
        jira-base-url: ${{ secrets.JIRA_BASE_URL }}
        jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
        jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        issuetypes: Story,Bug
        transitions: In Progress,In Progress